//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface Activity {
    entityName: string;
    recordId: number;
    activityType: string;
    userId: string;
    isActive: boolean;
    id: number;
    title: string;
    url: string;
    image: string;
    subtitle: string;
    publishedAt: Date;
    updatedAt: Date;
}