//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum SubscriptionStatus {
    Active = "active",
    Expired = "expired",
    Canceled = "canceled",
}

export interface Price {
    id: string;
    name: string;
    currency: string;
    amount: number;
    description: string;
    interval: string;
    nextBillingDate: Date | undefined;
}

export interface Billing {
    userId: string;
    subscriptionId: string;
    priceId: string;
    status: SubscriptionStatus | undefined;
    price: Price | undefined;
    id: number;
}